### ISSUE TITLE
option to auto-rename blacklisted method names

### ISSUE THREAD

**Issue by maxogden** [maxogden/observify#2]
e.g. `name` and `length` are blacklisted here https://github.com/Raynos/observ-struct/blob/master/index.js due to javascript reserved properties for method names

should there be an observify option to auto rename these with a customizable prefix that defaults to `$`, e.g. it would rename `name` to `$name`?

right now the user will get an error like:

```
cannot create an observ-struct with a key named 'name'.
Clashes with `Function.prototype.name`.
```

and then they will have to transform their source data manually

**Comment by ashnur** [comment]
I think this should be closed.
